# Generated by Django 4.1.3 on 2022-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MeMeFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'MeMeFiter',
                'verbose_name_plural': 'MeMeFiters',
            },
        ),
        migrations.CreateModel(
            name='MeMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('img', models.ImageField(upload_to='meme')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('create_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ManyToManyField(related_name='category', to='meme.category')),
                ('filters', models.ManyToManyField(related_name='meme_filters', to='meme.memefilters')),
            ],
            options={
                'verbose_name': 'Meme',
                'verbose_name_plural': 'Memes',
                'ordering': ['-create_on'],
            },
        ),
    ]
